# Generated by Django 5.2.7 on 2025-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=255, verbose_name='文件名')),
                ('utime', models.CharField(max_length=12, verbose_name='更新时间')),
            ],
        ),
    ]
