# Generated by Django 5.2.7 on 2025-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_fileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='utime',
            new_name='upload_time',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='uploade_user',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='上传用户'),
        ),
    ]
