# Generated by Django 5.2.7 on 2025-10-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_utime_fileinfo_upload_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='fname',
            new_name='file_name',
        ),
    ]
