# Generated by Django 5.2.7 on 2025-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_fname_fileinfo_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_size',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='文件大小'),
        ),
    ]
