# Generated by Django 5.2.7 on 2025-10-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_fileinfo_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='uploade_user',
            new_name='upload_user',
        ),
    ]
