# Generated by Django 5.2.7 on 2025-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_uploade_user_fileinfo_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
